添加对同步和异步hapi(老版和新版)中间件的支持，并添加Demo，完善readMe
ElemeFE/restc pull request #35
Opened 2019-05-14 11:21 UTC by MaySnow

2019-05-14 12:22 UTC, csvwolf commented
首先，建议参考 commits log 使用英文注释哦

2019-05-14 16:41 UTC, lujjjh requested changes
感谢贡献代码，提了一些修改建议还请看一下。

2019-05-14 16:41 UTC, lujjjh commented on examples/restc-example-hapi/old/index.js
> +      reply('Hello Word!')
`Word` -> `world`，下同

2019-05-14 16:41 UTC, lujjjh commented on examples/restc-example-hapi/old/index.js
> +  // 添加路由
其他注释都是英文，统一使用英文吧

2019-05-14 16:41 UTC, lujjjh commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
现在看来这个文件没什么意义，我会提一个 PR 去掉这个文件，直接给 `serve` 传入 Node 的 `req` 和 `res` 即可

2019-05-14 16:41 UTC, lujjjh commented on README.md
> +                }], (err) => {})
没写过 hapi，这里的 `(err) => {}` 是用来忽略错误的吗？为什么旧版本的 hapi 的推荐姿势是忽略错误？

2019-05-14 16:41 UTC, lujjjh commented on lib/hapiOld.js
> +'use strict'
hapi _old_ 是社区惯用说法吗？

2019-05-15 02:19 UTC, MaySnow commented on README.md
> +                }], (err) => {})
不是用来忽略错误的，当加载plugin的时候如果出错会抛出，项目启动失败，/restc/examples/restc-example-hapi/old/index.js，有具体的使用

2019-05-15 02:24 UTC, MaySnow commented on lib/hapiOld.js
> +'use strict'
这个不是社区的惯用说法，在17.x以下的版本用的是回调，17.x及以上版本支持async await，用法不同所以要分开来写，不过老的回调用法的人应该是比较少了

2019-05-15 02:29 UTC, MaySnow commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
这个文件如果去掉的话，从我调试最新版本的hapi来看，lib/index.js里handler方法的 return true，改成return content，对于hapi的插件开发会比较友好
`
// serve restc
    res.send(content)

    return true
`
改为
`
// serve restc
    res.send(content)

    return content
`

2019-05-15 02:34 UTC, MaySnow commented on examples/restc-example-hapi/old/index.js
> +      reply('Hello Word!')
已经修改

2019-05-15 02:34 UTC, MaySnow commented on examples/restc-example-hapi/old/index.js
> +  // 添加路由
已经修改

2019-05-15 02:40 UTC, lujjjh commented on lib/hapiOld.js
> +'use strict'
了解了，这个场景 old 换成 legacy 比较合适

2019-05-15 02:45 UTC, MaySnow commented on lib/hapiOld.js
> +'use strict'
那我再做一下修改

2019-05-15 03:15 UTC, lujjjh commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
我提了个 PR (#36)，看看 hapi 传入 `request.raw.req` 和 `request.raw.res` 是不是更友好？

2019-05-15 03:18 UTC, lujjjh commented on docs/guide/README.md
> +[restc-example-hapi-old]: https://github.com/ElemeFE/restc/tree/master/examples/restc-example-hapi/legacy
这里的 old 也替换一下？

2019-05-15 05:22 UTC, MaySnow commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
由于hapi的onPreResponse的response里并没有setHeader和end方法，所以我utils下增加了fromHapiContext.js用来给response增加setHeader和end，并做相应的处理。不同的框架对header的更改和最后渲染页面所用的方法可能不一样，所以我觉得以前的对response进行扩展的方法做的挺好的

2019-05-15 05:48 UTC, lujjjh commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
我调研了下包括 Koa 和 hapi 在内都有暴露 Node 的 `request` 和 `response` 对象（实现了 [`setHeader`](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_response_setheader_name_value) 和 [`end`](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_response_end_data_encoding_callback)），hapi 可以这么做：

```js
serve(options)(request.raw.req, request.raw.res)
```

对于不暴露（或者不基于 http 标准库）的框架确实得写个 adapter。

2019-05-15 06:19 UTC, MaySnow commented on lib/utils/response.js
> +exports.fromHapiContext = (request, reply, sendCallBack) => {
确实是我搞错了，已做了对应修改

2019-05-15 06:22 UTC, lujjjh commented on docs/guide/README.md
> +也可以参考我们提供的例子 [restc-example-hapi-old][restc-example-hapi-old]。
漏了一处，改了之后我先合一波你的 PR

2019-05-15 07:44 UTC, MaySnow commented on docs/guide/README.md
> +也可以参考我们提供的例子 [restc-example-hapi-old][restc-example-hapi-old]。
已做修改

2019-05-15 07:44 UTC, MaySnow commented on docs/guide/README.md
> +[restc-example-hapi-old]: https://github.com/ElemeFE/restc/tree/master/examples/restc-example-hapi/legacy
已做修改

2019-05-15 08:11 UTC, lujjjh approved these changes

2019-05-15 08:12 UTC, merged